version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  php:
    build: ./docker/php
    ports: ['9000:9000']
    restart: always
    volumes: ['./symfony/backend:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['30180:80']
    restart: always
    volumes: ['./symfony/backend:/var/www/symfony:cached']

  portainer:
    image: portainer/portainer
    ports:
      - "30179:9000"
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  jenkins:
   image: jenkins/jenkins:lts
   privileged: true
   user: root
   ports:
     - 30181:8080
     - 30182:50000
   container_name: jenkins
   volumes:
     - ./jenkins_data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock


volumes:
  portainer_data:

