version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./symfony/backend:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['30180:80']
    volumes: ['./symfony/backend:/var/www/symfony:cached']

  portainer:
    image: portainer/portainer
    ports:
      - "30179:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
